sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo add-apt-repository -y ppa:laczik/ppa
  - sudo apt-get update -qq
  - sudo apt-get install sdcc

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip -O IntrOS-master.zip
  - unzip -q -d . IntrOS-master.zip IntrOS-master/IntrOS/kernel/*
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/

before_script: sdcc --version

script: make all SDCC= -f makefile.sdcc

group: stable
