sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
  - sudo apt-get install -y curl subversion build-essential flex bison libboost-dev texinfo stx-btree-dev zip netcat gawk python2.7
  - mkdir sdcc-code -p
  - cd sdcc-code
  - svn checkout svn://svn.code.sf.net/p/sdcc/code/trunk/sdcc@10039
  - cd sdcc
  - ./configure --disable-pic14-port --disable-pic16-port
  - make && make install
  - cd ..
  - cd ..
  - rm -Rf sdcc-code

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - rm -r IntrOS-master

before_script: sdcc --version

script: make all SDCC= -f makefile.sdcc

group: stable
