sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
  - wget https://netcologne.dl.sourceforge.net/project/sdcc/sdcc-linux-x86/3.6.0/sdcc-3.6.0-i386-unknown-linux2.5.tar.bz2
  - tar xjf sdcc-3.6.0-i386-unknown-linux2.5.tar.bz2
  - mv -t /usr/local sdcc-3.6.0/*
  - rm -r sdcc-3.6.0

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip -O IntrOS-master.zip
  - unzip -q -d . IntrOS-master.zip IntrOS-master/IntrOS/kernel/*
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/


script: make all SDCC=/usr/local/bin/ -f makefile.sdcc

group: stable
